### ISSUE TITLE
Program always fails due to hang

### ISSUE THREAD

**Issue by msftsecurityteam** [ivanfratric/winafl#1]
Before I run the afl-fuzz I am able to run my target executable with drrun.exe. But no matter what I do with the timeout passed to afl-fuzz.exe, the test case always results in a hang.  Any suggestions to check out?

**Comment by ivanfratric** [comment]
Would you mind sharing your log file from drrun.exe run and the command line you are using? Problems like this can be caused by an incorrect target offset. A hang in winafl means that the target didn't respond correctly which can happen because of a timeout but can also happen for other reasons (I realize error messages might be misleading in those cases).

**Comment by msftsecurityteam** [comment]
Hi Ivan, thanks for the suggestions!  I actually got it working because I was using the offset in the file for the WinMain function, and not the actual offset from the image module base.  Now that I have the correct nargs and target_offset it is working great!

**Comment by the-st0rm** [comment]
@msftsecurityteam  I think I am facing the same problem .. how can I get the actual offset from the image module base??  I am trying to fuzz the main function .. I opened IDA Pro and the address of the function something similar to `.text:00000000004014F0` then I used the offset to be 0x14F0 but I still getting time outs ..
