### ISSUE TITLE
System Error: Unable to create 'out\.cur_input'

### ISSUE THREAD

**Issue by bytems** [ivanfratric/winafl#13]
Hello ivanfratric

I installed WinAFL and it mostly seems to be running well. However after the WinAFL runs for some time, I get the following System Error message.

![image](https://cloud.githubusercontent.com/assets/16283344/18857379/40afdd76-8418-11e6-9f8a-14fdd7c360b3.png)

I am running the WinAFL tool as an Administrator, so I do not know why the OS denies permission.

Any thoughts?

**Comment by ivanfratric** [comment]
It seems that WinAFL was unable to write a new sample file over existing one. When that happens, WinAFL first attempts to kill the target process and then attempts to overwrite the file again. So the error you see can be one of two things:
 - Either WinAFL was unable to kill the target process or
 - The input file was open in such a way that even killing the target process didn't help to release it.
I'm curious to see which one it was. When that happens, can you check if you can delete the .cur_input file and check in the task manager if the target process is still running and try to kill it from there?

The only workaround for now is to restart WinAFL and resume the fuzzing session. You can resume the session by using '-i -' instead of your input directory (same as Linux AFL).

In the future versions, it might be possible to resolve issues like this by falling to another input file if deleting the current one fails repeatedly (e.g. .cur_input1, .cur_input2 etc.)

**Comment by bytems** [comment]
So I ran WinAFL again to follow your suggestions and here are my observations.

When the tools reaches a hang, the following pops up:
![image](https://cloud.githubusercontent.com/assets/16283344/18975423/dbab0c40-865e-11e6-887a-452c19f13132.png)
Selecting cancel results in the system error message I talked about in the beginning of the issue.
However, if I don't select cancel. The tool does keep on running, and the `'.cur_input'` file keeps on getting updated. As such, if I try to delete the `'.cur_input'` file, a window pops up explaining that the deletion cannot be carried through because the file is open in another program.
Ending the task in "Task Manager" kills the target process and gets rid of the messages (shown above), and WinAFL still runs. Which is great.

Thanks ivanfratric. I believe the issue has been resolved.
