### ISSUE TITLE
Changing the Memory Limit

### ISSUE THREAD

**Issue by bytems** [ivanfratric/winafl#16]
Hello ivanfratric

How would one go about changing the memory limit of the WinAFL tool.

Would changing the memory limit in **config.h** work?

```
/* Default memory limit for child process (MB): */
55  
56  #ifndef __x86_64__ 
57  #  define MEM_LIMIT         25
58  #else
59  #  define MEM_LIMIT         50
60  #endif /* ^!__x86_64__ */
```

**Comment by ifratric** [comment]
WinAFL can't change the memory limit of the target process. If you need to enforce a memory limit you need to build a custom solution for your target.

**Comment by bytems** [comment]
Hmm OK. Well, the main reason why I raised this issue is because, all the test cases generated by WinAFL in the crash folder (the ones that caused the target to crash during the WinAFL run). When I actually individually ran those test cases straight to the target, none of them crash the target.  
Basically I can't reproduce the crashes found by WinAFL. The AFL readme file suggested that changing memory limit might resolve this issue.

**Comment by bytems** [comment]
I can't reproduce the crashes found by WinAFL. Running the individual test cases (in the crashes folder) against my target binary does not result in a crash or segmentation fault.
Can this happen, or am I doing something wrong?

**Comment by ivanfratric** [comment]
There are several reasons this could be happening. For reference, take a look at the onexception() function inside winafl.c to see how WinAFL catches crashes. Some possibilities:
 - The exception is caught by your target so it doesn't crash. In this case you should still see an exception if you run the target with a debugger. You can also run the "crashing" sample in the WinAFL debug mode and the most recent version is going to report encountered exceptions in the debug log.
 - Since WinAFL uses persistent mode, it is possible that some of the previous samples put your target in a state where a subsequent state caused a crash. In the simple case it could be that previous samples exhausted the memory of the target process, a subsequent sample tried to allocate memory and failed which caused a crash. But it could also mean more serious incorrect states. You can run WinAFL with lesser number of fuzz_iterations. In the extreme case you can set fuzz_iterations to 1 which will restart a process for every sample (needless to say that's going to run much slower). You can also take a corpus provided by WinAFL and run it through some other, non-coverage-guided fuzzer in order to try to rediscover a crash.

**Comment by ivanfratric** [comment]
I'm closing this issue since memory limit support was added in 1.11
