### ISSUE TITLE
Cannot change input file extensions

### ISSUE THREAD

**Issue by nevermoe** [ivanfratric/winafl#26]
Hi, I am fuzzing this soft called VUPlayer. This software requires the file extension to be `m3u` to work. So I am trying to change the input file name to `xxx.m3u` otherwise the input file name will be `.cur_input` and no crash will be made even using a poc input. I am using the following command to achieve this purpose but it seems I failed since it keeps telling me `1 process nudged` and `Succeeded terminating process with PID xxxx`. Am I using the `-f` option in a bad way?

```
C:\Program Files (x86)\VUPlayer> afl-fuzz.exe -i in -o out -f test.m3u -D C:\Users\Administrator\Desktop\DynamoRIO-Windows-6.2.0-2\bin32 -t 20000 -- -fuzz_iterations 5000 -coverage_module VUPlayer.exe -target_module VUPlayer.exe -target_offset 0x532a0 -nargs 2 -- UPlayer.exe @@
```

**Comment by ivanfratric** [comment]
That's how -f flag should work. Are you saying that it behaves differently with the same command line but without -f flag?  Though you also said that the input needs to have .m3u extension so that could also explain the difference in behavior (since .cur_input might not be processed at all).

The messages you receive could be due to your target function not closing input file before it returns, in which case WinAFL must kill the whole process in order to rewrite the input file. Perhaps some other target function less deep in the stack can be used?

**Comment by mrpeppels** [comment]
> The messages you receive could be due to your target function not closing input file before it returns

This^.

does you debug log follow this pattern?:

In pre_fuzz_handler
In OpenFileW, reading ..\..\o\.cur_input
In post_fuzz_handler

the program should 1)trigger the target method 2) completely process the file 3) return and trigger the post-fuzz handler

**Comment by nevermoe** [comment]
Hi, thank you guys @mrpeppels, @ivanfratric . I think I begin to understand a little about the fuzzer. So I tried to find another offset that contains a complete `Open` and `Close` procedure. I Used the following command:

```
afl-fuzz.exe -i in -o out -f crash.m3u -D C:\Users\Administrator\Desktop\DynamoRIO-Windows-6.2.0-2\bin32 -t 20000 -- -fuzz_iterations 5000 -coverage_module VUPlayer.exe -target_module VUPlayer.exe -target_offset 0x8cc10 -nargs 2 -- VUPlayer.exe @@
```

However, this time the afl will quit immediately and suggest that a crash happened. But I believe my input file is legal and if I open my input file with VUPlayer directly, it can be parsed correctly without crash.

Then I tried to run VUPlayer with `drrun` and get the following log. The dyanamo also suggest that VUPlayer is crashing. I'm a little bit confused.

```
Module loaded, NetworkExplorer.dll
Module loaded, LINKINFO.dll
Module loaded, mssprxy.dll
In OpenFileW, reading C:\Program Files (x86)\VUPlayer\in\test.m3u
In pre_fuzz_handler
In post_fuzz_handler
In pre_fuzz_handler
Exception caught: c0000005
crashed
Everything appears to be running normally.
Coverage map follows:
```

For some additional information, the function at offset 0x8cc10 is like this:

```
int __thiscall sub_48CC10(_DWORD *this, char *a2)
{
 ...
  if ( v43 < 260 && CStdioFile::Open((CStdioFile *)&v63, a2, 0x4040u, 0) )
  {
    ....
    CStdioFile::Close((CStdioFile *)&v63);
    ....
  }
  ...
}
```

**Comment by ivanfratric** [comment]
I see two problems in your debug log,

1. It looks like your input file was opened outside of the target function (otherwise you'd see the file being opened between pre_fuzz_handler and post_fuzz_handler). It looks like it got opened *before* the target function was reached.

2. Your target crashed on the second pass of the target function. This could indicate that the first pass did something that messed up the second pass. WinAFL attempts to restore parameters of the target function (that's what -nargs flag is used for) but unfortunately doesn't know how to restore anything else (as this would be highly target-specific).

I suggest finding the function that opened the input file and trying to use that one for target_offset.

**Comment by nevermoe** [comment]
Thank you for suggestion. But I am sure the target_function is called and opened the exact input file because I debugged it. And I get the following log (it's a little different from the last one and I don't know why.). In this log what does `OpenFileW` and `OpenFileA` mean? Thank you.
```
Module loaded, dwmapi.dll
Module loaded, OLEACC.dll
Module loaded, POWRPROF.dll
Module loaded, DSOUND.dll
In OpenFileW, reading C:\Program Files (x86)\VUPlayer\VUPlayer.exe
Module loaded, MMDevAPI.DLL
In OpenFileW, reading C:\Program Files (x86)\VUPlayer\VUPlayer.exe
Module loaded, AudioSes.DLL
In OpenFileW, reading C:\Program Files (x86)\VUPlayer
In OpenFileA, reading \\.\D:
In pre_fuzz_handler
In post_fuzz_handler
In pre_fuzz_handler
Exception caught: c0000005
crashed
Everything appears to be running normally.
Coverage map follows:
```

**Comment by nevermoe** [comment]
Hi, I test your `test_gdiplus` with the following command, it still not works. 

```
C:\Users\Administrator\Desktop\winafl-master\bin64> C:\Users\Administrator\Desktop\DynamoRIO-Windows-6.2.0-2\bin64\drrun.exe -c winafl.dll -debug -fuzz_iterations 10 -target_module test_gdiplus.exe -target_offset 0x1270 -nargs 2 -- test_gdiplus.exe test.bmp
```

The log file is like:
```
Module loaded, GDI32.dll
Module loaded, ntdll.dll
In pre_fuzz_handler
Module loaded, UxTheme.dll
Module loaded, tiptsf.dll
Module loaded, OLEAUT32.dll
Module loaded, WindowsCodecs.dll
In post_fuzz_handler
In pre_fuzz_handler
In post_fuzz_handler
In pre_fuzz_handler
In post_fuzz_handler
In pre_fuzz_handler
In post_fuzz_handler
In pre_fuzz_handler
In post_fuzz_handler
In pre_fuzz_handler
In post_fuzz_handler
In pre_fuzz_handler
In post_fuzz_handler
In pre_fuzz_handler
In post_fuzz_handler
In pre_fuzz_handler
In post_fuzz_handler
In pre_fuzz_handler
In post_fuzz_handler
Everything appears to be running normally.
Coverage map follows:
```
, which suggest that the `bmp` file was not opened at all. I don't know why even the sample doesn't work.

**Comment by ivanfratric** [comment]
Are you on Windows 10 by any chance? I noticed that on Windows 10 a different api is used for file opening so you wouldn't necessarily see a file being opened in the debug log.

To answer your earlier question: OpenFileW/OpenFileA should actually be CreateFileW/CreateFileA (that's a mistake I made in the debug messages). CreateFile[W|A] is a Windows API for opening files. 'A' refers to the Ascii and 'W' to the wide char version.

**Comment by nevermoe** [comment]
I'm in fact on Windows 8. Anyway, this still can't explain why the log tells me it (VUPlayer) crashes at the second iteration. (It seems the target function is reached and I have tried `nargs` from 0 to 7 although I believe the right number may be 3).

**Comment by ivanfratric** [comment]
No idea how Windows 8 behaves, I only tested on 7 and 10, though it's quite possible that 8 and 10 use the same API.

For (possible) explanation of crashing on the second iteration see point 2 in https://github.com/ivanfratric/winafl/issues/26#issuecomment-255203210. Note that this might be unrelated to the function arguments (for example: One of the function arguments might be a pointer and WinAFL will restore that argument, but it cannot restore data pointed by that pointer. That's why WinAFL works best if the target function is relatively self-contained).

**Comment by nevermoe** [comment]
Sorry, what do you mean by "self-contained"? If a function contains a pointer (which is very likely to happen), do you mean the data pointed by the the pointer can't be restored? If that is the case, any function which take a `char*` (e.g. a file name) as a argument can't be used as target function? In the example `test_gdiplus` program, the main function also has a `char *` type argument, why the test works fine?

**Comment by ivanfratric** [comment]
Because the target function doesn't change the data that char* points to. I'm not saying the function can't dereference any pointers, just that if a function writes to memory pointed by the pointer and another call of the same function reads from the same pointer and expects the data is initialized in a certain way, there might be problems.

**Comment by nevermoe** [comment]
Thank you very much! I think I understand what's happening now! I changed my target function to the main function and finally get winafl worked! I read a little source code and finally realized what is winafl doing. It tries to avoid restarting the target program and re-execute the process by resetting the pc register in order to save time. That may cause problem if the memory is corrupted at the following iterations.  Thank you again!

**Comment by nevermoe** [comment]
Sorry, one more question. Whatever my input file is, the mutated file is always a very small (under 1kb). Is this normal?

**Comment by nevermoe** [comment]
I restart my computer and this it works fine again. It seems that when I terminate the winafl process using ctrl-c, the winafl isn't closed correctly and somehow affect the mutator from working normally. It doesn't recover untill I restart the computer.

**Comment by ivanfratric** [comment]
Small input file: Don't know if that is the case here but I think afl-fuzz might be trying to trim input files and get a smaller version that has the same coverage.

Can you clarify what you mean by "winafl isn't closed correctly" and "affect the mutator from working normally". Presumably after ctrl-c the afl-fuzz process (and with it, all the mutators) is killed so I'm not sure how that would affect subsequent runs and what difference would restarting the computer make.

**Comment by nevermoe** [comment]
I don't know either. It should be terminated. I have checked the task manager after ctrl-c, and no afl-fuzz nor VUPlayer.exe process is in the task manager. This indicate afl-fuzz is terminated correctly. However, without a restart of computer, I can't even open VUPlayer standalone (without using alf-fuzz) again. I guess this might be some bug of windows, maybe not related to winafl.

After one day of fuzzing, my result looks like this:
![winafl](https://www.nevermoe.com/wp-content/uploads/2016/10/%E3%82%AD%E3%83%A3%E3%83%97%E3%83%81%E3%83%A3.png)

It looks strange that the `cycles done` is very big while `new path` is only 2. Besides the `last new path` suggest "odd, check syntax!" which I don't know what is meaning. It seems afl is not working as I expected. Would you please tell me what does cycles and path mean? And what does the "odd, check syntax!" indicate?

I also noticed another question that although you said win 8/10 might use another API for opening file, I can still see the file be opened by CreateFileW if I use a poc input (a input that make VUPlayer crash). On the other hand, if I give it a normal input, no message will be printed between `pre_fuzz_handler` and `post_fuzz_handler`. I am so confused now.

**Comment by ivanfratric** [comment]
This looks odd because it seems that WinAFL is not finding new coverage. You only have 2 sampes with new coverage (that's what 'total paths' means) and WinAFL is constantly iterating over only those 2 samples ('cycles done' indicates a number of passes over all interesting samples). I would check that
a) your target function performs input file parsing
b) your coverage_module flag points to the module that performs input file parsing.

**Comment by nevermoe** [comment]
Yes, I only have 2 samples so maybe it makes sense? However, I think maybe my target function is not good. I set my target function to `WinMain` and when I started winafl it will open the VUPlayer's UI. So I shutdown the VUPlayer's UI and the fuzzer will go on.

Do you know if this behavior is normal? If the pc register is reset to the beginning of the target function (`WinMain` in this case) in every pass, shouldn't the UI be turned on in every pass?

**Comment by nevermoe** [comment]
Hi, I found something interesting. You used `drwrap_wrap` to set the `pre_fuzz_handler` and `post_fuzz_handler`. But I found that this `drwrap_wrap` can only be used to hook the default calling convention on a platform. In the case of windows, it can only hook `cdecl` calling. However, in VUPlayer, most function call are `stdcall` including `WinMain` and the ones which caused crash in the second iteration that I have tried. So I guess maybe this is the problem? Can you provide a option to choose the calling convention of the target function using like `drwrap_wrap_ex`?

**Comment by mrpeppels** [comment]
About your last point; no because WinMain does not return by itself. The trick is to find the function that parses the file, and then returns without user interaction. The coverage module will also probably not be the main executable, but the dll used to handle the specific file format you're targeting.

**Comment by nevermoe** [comment]
Ok, thank you.  I guess I'd better try another target, a easier one.
