### ISSUE TITLE
division-by-zero ignored?

### ISSUE THREAD

**Issue by trylab** [ivanfratric/winafl#28]
```
https://github.com/ivanfratric/winafl/blob/master/winafl.c#L175
```
It seems that exception 0xC0000094 (division-by-zero) is ignored by winafl which will cause hangs and a window will be prompted by WerFault.exe.

Will we consider handle this exception?

Thanks.

**Comment by ivanfratric** [comment]
Hi, I didn't include division-by-zero initially because most of the time it won't be security relevant. Currently division-by-zero (as well as any other uncought exceptions that are not explicitly on the list) should be treated as a hang. If people think it makes sense to include it I can add it in the next update.

**Comment by trylab** [comment]
Hello, I agree with you that it's not security related, but I think software developers are interested in such bugs and will be happy to fix them. 

Another reason is that a warning dialog will be prompted by WerFault.exe when the program encountered such bugs. 

Thanks.

**Comment by ivanfratric** [comment]
This exception type is now being catched.
